// THIS ENUMS ARE SHARED BY EXTHIUMWORLD SERVER & CLIENT
// EVERY GAME ACTION NEEDS TO BE DECLARED HERE FIRST

export enum ACTIONS {
  CREATE_DIMENSION = 'CREATE_DIMENSION',
  INITIATE_WORLD = 'INITIATE_WORLD',
  GET_WORLD = 'GET_WORLD',
  GET_WORLD_TILES = 'GET_WORLD_TILES',
  GET_WORLD_TILE = 'GET_WORLD_TILE'
}
